image: nkx1231/root6-geant4-garfield:0.4

variables:
    GIT_SUBMODULE_STRATEGY: recursive
  
before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  
stages:
  - build
  - simulation

build:
  type: build
  script:
    - echo "**${CI_PROJECT_DIR}**"
    - rm -rf ${CI_PROJECT_DIR}/install
    - git clone git@lfna.unizar.es:rest-development/REST_v2.git REST_v2
    - cd REST_v2/
    - git checkout development
    - mkdir build
    - cd build
    - cmake ../ -DREST_WELCOME=ON -DREST_GARFIELD=OFF -DREST_G4=ON -DINSTALL_PREFIX=${CI_PROJECT_DIR}/install
    - make install -j2
    - cd ${CI_PROJECT_DIR}
    - source ${CI_PROJECT_DIR}/install/thisREST.sh
    - restRoot -b -q
    - rest-config --commit
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/install
    expire_in: 1 day
  
simulation:
  type: simulation
  script:
    - source ${CI_PROJECT_DIR}/install/thisREST.sh
    - export MAIN_DIR=${CI_PROJECT_DIR}
    - ls -lht ${MAIN_DIR}/geometry
    - bash ${CI_PROJECT_DIR}/simulations/cosmic_neutrons/test/simulation_babyiaxo_in_between.sh
  artifacts:
    paths:
      - /tmp/test_simulations
    expire_in: 1 day
      
      
      
  